version: 0.0
os: linux

hooks:
  # 1. 'BeforeInstall': 파일 복사(Install) 단계 직전에 실행됩니다.
  BeforeInstall:
    - location: scripts/clean_directory.sh # 기존 폴더를 청소하는 스크립트
      timeout: 300
      runas: root # root 권한으로 실행
      
  # 2. 'ApplicationStart': 모든 배포가 완료된 후 실행됩니다.
  ApplicationStart:
    - location: scripts/restart_server.sh # 웹 서버를 재시작하는 스크립트
      timeout: 60
      runas: root

files:
  - source: /
    destination: /var/www/html/gnuboard5
    overwrite: true # 덮어쓰기 허용 (기존 파일 삭제 로직과 함께 사용)

permissions:
  - object: /var/www/html/gnuboard5
    pattern: "**"
    owner: apache
    group: apache
    mode: 644
  - object: /var/www/html/gnuboard5/data
    pattern: "**"
    owner: apache
    group: apache
    mode: 755
